name: Run Python Script on Schedule

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GSHEETS_BASE64: ${{ secrets.GSHEETS_BASE64 }}  # Google Sheets credentials
      TOKEN: ${{ secrets.TOKEN }}  # API authentication token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decode Google Sheets JSON
        run: echo "$GSHEETS_BASE64" | base64 --decode > client_secret.json

      - name: Debug Environment Variables
        run: |
          echo "TOKEN is ${TOKEN:0:5}*****"
          echo "Decoded Google Sheets credentials stored as client_secret.json"

      - name: Run script
        run: python saf_edited.py
